### ISSUE TITLE
error: reference to __host__ function 'inclusive_scan<rocprim::default_config, double *, double *, thrust::plus<double>>' in __host__ __device__ function

### ISSUE THREAD

**Issue by qili93** [ROCmSoftwarePlatform/rocPRIM#202]
**Describe the bug**

error: reference to __host__ function 'inclusive_scan<rocprim::default_config, double *, double *, thrust::plus<double>>' in __host__ __device__ function

**To Reproduce**
1. Install '...' version '...'
2. Run '...' with data '...'
3. See error on logfile '...'

Implemented an device function below, and compiler error comes out in ROCM3.5.1
```c++
template <typename T>
__global__ void GetCumulativeProbs(T* norm_probs_data,
                                   int64_t num_distributions,
                                   int64_t num_categories,
                                   T* cumulative_probs) {
  for (int id = blockIdx.x; id < num_distributions; id += gridDim.x) {
    thrust::inclusive_scan(thrust::device,
                           norm_probs_data + id * num_categories,
                           norm_probs_data + (id + 1) * num_categories,
                           cumulative_probs + id * num_categories);
  }
}
```

**Expected behavior**

**Log-files**
Add *full* logfiles to help explain your problem.

```log
In file included from /workspace/Github-qili93/Paddle/paddle/fluid/operators/multinomial_op.cu:15:
In file included from /opt/rocm/include/thrust/execution_policy.h:31:
In file included from /opt/rocm/include/thrust/system/cpp/execution_policy.h:64:
In file included from /opt/rocm/include/thrust/system/cpp/detail/sort.h:22:
In file included from /opt/rocm/include/thrust/system/detail/sequential/sort.h:63:
In file included from /opt/rocm/include/thrust/system/detail/sequential/sort.inl:23:
In file included from /opt/rocm/include/thrust/system/detail/sequential/stable_primitive_sort.h:55:
In file included from /opt/rocm/include/thrust/system/detail/sequential/stable_primitive_sort.inl:21:
In file included from /opt/rocm/include/thrust/system/detail/sequential/stable_radix_sort.h:55:
In file included from /opt/rocm/include/thrust/system/detail/sequential/stable_radix_sort.inl:20:
In file included from /opt/rocm/include/thrust/copy.h:513:
In file included from /opt/rocm/include/thrust/detail/copy_if.h:74:
In file included from /opt/rocm/include/thrust/detail/copy_if.inl:20:
In file included from /opt/rocm/include/thrust/system/detail/generic/copy_if.h:63:
In file included from /opt/rocm/include/thrust/system/detail/generic/copy_if.inl:31:
In file included from /opt/rocm/include/thrust/scan.h:1563:
In file included from /opt/rocm/include/thrust/detail/scan.inl:28:
In file included from /opt/rocm/include/thrust/system/detail/adl/scan.h:44:
/opt/rocm/include/thrust/system/hip/detail/scan.h:193:19: error: reference to __host__ function 'inclusive_scan<rocprim::default_config, float *, float *, thrust::plus<float>>' in __host__ __device__ function
        (rocprim::inclusive_scan<rocprim::default_config, InputIt, OutputIt, ScanOp>)
                  ^
/opt/rocm/include/rocprim/device/device_scan.hpp:529:12: note: 'inclusive_scan<rocprim::default_config, float *, float *, thrust::plus<float>>' declared here
hipError_t inclusive_scan(void * temporary_storage,
           ^
3 warnings and 2 errors generated when compiling for gfx906.
CMake Error at multinomial_op_generated_multinomial_op.cu.o.cmake:192 (message):
  Error generating file
  /workspace/Github-qili93/Paddle/build_rocm_nccl/paddle/fluid/operators/CMakeFiles/multinomial_op.dir//./multinomial_op_generated_multinomial_op.cu.o
```

**Environment**
Make sure that ROCm is correctly installed and run the following command:
```
printf '=== environment\n' > environment.txt && 
printf '\n\n=== date\n' >> environment.txt && date >> environment.txt && 
printf '\n\n=== Linux Kernel\n' >> environment.txt && uname -a  >> environment.txt && 
printf '\n\n=== rocm-smi' >> environment.txt && rocm-smi  >> environment.txt && 
printf '\n\n' >> environment.txt && hipconfig  >> environment.txt && 
printf '\n\n=== rocminfo\n' >> environment.txt && rocminfo  >> environment.txt && 
printf '\n\n=== lspci VGA\n' >> environment.txt && lspci | grep -i vga >> environment.txt
```

Attach `environment.txt`

**Additional context**

**Comment by xuhuisheng** [comment]
it said that you cannot invoke a host only function in a both of host and device valid function. because the outer function maybe run in device environment.

**Comment by neon60** [comment]
Tested the function it's working for me with rocm 4.1:
https://github.com/ROCmSoftwarePlatform/rocThrust-tests/pull/8
